### ISSUE TITLE
how to use txt2mask?

### ISSUE THREAD

**Issue by WeiWenxing** [ThereforeGames/unprompted#100]
is there a guide to use txt2mask?

**Comment by WeiWenxing** [comment]
[txt2mask mode="add" precision=100.0 padding=0.0 smoothing=20.0 neg_precision=100.0 neg_padding=0.0 neg_smoothing=20.0 sketch_alpha=100 sketch_color="0,127,0"]dress[/txt2mask]green dress

The prompts is as above,  in img2img->sketch,  I attempt to instead of the 'dress' as 'green dress' to change the color of the dress in a photo.

The dress changed,  but color not work, it's still red.

**Comment by ThereforeGames** [comment]
Hi @WeiWenxing,

If the dress is correctly selected with `[txt2mask]` but the color isn't changing, then the issue is related to your inference settings rather than Unprompted. You may need to increase your denoising strength, CFG scale, try a different masked content mode, etc.

The only potential issue I see in the shortcode is the `sketch_alpha` value - at 100 it is partially transparent, so maybe you can try raising it to 255 for an opaque mask.

But if that doesn't help, I would recommend opening a discussion thread for further suggestions.
