### ISSUE TITLE
Handling sampler_name and steps

### ISSUE THREAD

**Issue by entusiastaIA** [ThereforeGames/unprompted#127]
Hello, I was trying to make prompt dependant the webui sampler_name and steps variables when making a multiple batch count set. But they don't change anymore after being choosen for the first time. You can reproduce it making a batch count of any number of images and launching the prompt with this very basic code inside of it:

[choose]
{set sampler_name}Heun{/set}
{set sampler_name}Euler a{/set}
[/choose]

You'll see that depending on the initial seed one of them both is picked at random, but all the remaining images are made with the same sampler, so in new images "choose" are ignored

**Comment by TheCulprit** [comment]
I believe all SD variables are only being set the first time. The [choose] is being run again but the effect of the set just isn't applying.

Doing 
```
[choose]
	{set width}512{/set} {set height}768{/set}
	{set width}768{/set} {set height}512{/set}
[/choose]
```
Will only apply first batch instead of every batch, making all images portrait or all images landscape instead of randomly selecting between them for each batch.

Doing
```
[set seed]31337[/set]
```
Should use 31337 as the seed for every batch, as far as I'm aware but instead it only applies to the first batch, the next batch will be random (presumably because the seed is set to -1 in the UI) and subsequent batches from then on are the previous seed + 1 which is the normal, weird behaviour of Unprompted but that's another issue.

**Comment by ThereforeGames** [comment]
Hi @entusiastaIA and @RetroBum,

As of Unprompted v9.8.0, the batch processing routines have been rewritten to support changes to Stable Diffusion variables between each image generation. This includes the checkpoint, sampler, CFG scale and theoretically everything else. Please let me know if it gives you any trouble.

> subsequent batches from then on are the previous seed + 1 which is the normal, weird behaviour of Unprompted but that's another issue.

This behavior is determined by the WebUI, not Unprompted. The WebUI does not refer to the `seed` variable for subsequent image generations, instead it refers to `all_seeds` which is populated by incremented values.

To get around this, you can either use the special variable `single_seed` or set the `all_seeds` array to one value, e.g. `[array all_seeds _fill=1000]`. Look up "single_seed" in the manual for more info.
