### ISSUE TITLE
Can't get ControlNet to work

### ISSUE THREAD

**Issue by MotherSoraka** [ThereforeGames/unprompted#133]
Hi, no matter what i do i cant use ControlNet through unprompted, i did read the manual, renamed my controlnet models, copied the yaml file and renamed that one too... but still no use.

can someone show me a simple example please?

**Comment by ThereforeGames** [comment]
Hi @MotherSoraka,

Documentation on using ControlNet is available in the "Special Variables" section of the Unprompted manual. Please also see this post for a simple example: https://github.com/ThereforeGames/unprompted/issues/102#issuecomment-1666160659

Finally, make sure to rename your `unprompted` extension folder to `_unprompted` so that CN plays well with Unprompted. This is due to [a limitation in the Automatic1111 extension framework](https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/8011) whereby priority is determined alphabetically.
