### ISSUE TITLE
[Bug]: Negative prompts in the styles csv don't work.

### ISSUE THREAD

**Issue by MrKuenning** [ThereforeGames/unprompted#157]
I used to have a bunch of complex negative prompts stored in the styles.csv file.
I have always been able to select whichever negative prompt I want, and it would apply.

Today I noticed that when I used unprompted, images generated did NOT change when selecting a negative style, unless I hit the button to "Apply the selected styles to the prompt"

1. Add a negative prompt to the styles sheet.
2. IMAGE 1 - Generate an image
3. IMAGE 2 - Generate the same seed with the negative style selected
4. IMAGE 3 - Apply the style to the prompt and generate the same image again.

In my case, I get the same image on IMAGE #1 and #2 and a new image on IMAGE #3
It should have changed on to a new image on IMAGE #2 instead.

**Comment by entusiastaIA** [comment]
As a dirty temporary fix you can store your negative prompt into a variable and hardcode a call to that variable in the default negative within de config file. Is what I'm doing and it works, but is dirty dirty.

**Comment by ThereforeGames** [comment]
Hi,

Unprompted should play nicely with negative prompt styles in v10.1.1. Let me know if it continues giving you any trouble. Thanks!

**Comment by entusiastaIA** [comment]
Hello there! Thank you very much for the quick update. Seems like it has improved a lot, but there's still an issue. Now the images are generated and processed, but when enabling hi res fix seems like if the prompt for the first image got stuck and applied to all the images (despite the text files generated state that they have the correct prompt). Look, these are the images without enabling hires fix and batch count 3 (I edited one to remove NSFW stuff):

![927807304-512x512-20231029_130308_878099](https://github.com/ThereforeGames/unprompted/assets/113212323/e106a797-0f67-4952-963f-dbbf26a68b6d)

![927807305-512x512-20231029_130311_475934](https://github.com/ThereforeGames/unprompted/assets/113212323/70cf72e2-17a9-41db-8798-0c80a73c277a)

![927807306-512x512-20231029_130313_189880](https://github.com/ThereforeGames/unprompted/assets/113212323/562d2d32-3706-4b8a-891d-1894845e0819)

And these are the same seeds after enabling high res fix:

![927807304-1024x1024-20231029_130226_584184](https://github.com/ThereforeGames/unprompted/assets/113212323/35fa2a81-3ebb-43c3-8c31-4ee8dffa5938)

![927807305-1024x1024-20231029_130240_965271](https://github.com/ThereforeGames/unprompted/assets/113212323/74b1cbb0-3901-4f22-8b73-5d9ab13f28de)

![927807306-1024x1024-20231029_130254_514155](https://github.com/ThereforeGames/unprompted/assets/113212323/7d118995-db42-443a-b340-73b4926ea6f1)

You can pretty much tell that is the prompt for the first one the one that is being used again and again, despite the text files with the prompts inside stating otherwise. For example the last uses "amidst a river with clear waters."; obviously the 512 image is obeying that, while the 1024 is obeying the place from the first image: "amidst an airport terminal."

Again, thank you very much.

**Comment by entusiastaIA** [comment]
Damn I wroyte into the wrong issue! Sorry, this is for the broken prompt interaction issue, sorry a lot, I don't think I can move it!

What a noob I am...
