### ISSUE TITLE
Small request to limit decimal place precision for random floats

### ISSUE THREAD

**Issue by magicbot42** [ThereforeGames/unprompted#169]
I often use (xxxx:[random _min=0.01 _max=0.1 _float]) to vary weights to tokens / loras, but its like 9 decimal places of precision and all of those numbers show up in the prompt.  prompt becomes a bit unreadable and don't really need that precision.  wondering if we could put a simple _precision flag into the shortcode to limit precision to something like _precision=2 if you want 2 decimal places of precision only. 

Thanks again for the amazing plugin.

**Comment by ThereforeGames** [comment]
Hi @magicbot42,

Thank you for your suggestion!

After giving it some thought, I have decided to implement `[round]` as its own shortcode rather than as a kwarg of `[random]`. The reason is that it may be desirable to round numbers obtained outside of `[random]`.

You can use it like this:

```
[round "{random _min=0.1 _max=0.9 _float}" _place=1]
```

Where `_place` is the decimal place limit.

In the interest of making this shortcode as versatile as possible, I made sure it also accepts whole numbers. For example, `[round 1344 _place=1]` will give you `1340`.

This shortcode is available in Unprompted v9.7.0.

Let me know if you have any questions. Have fun. :)
