### ISSUE TITLE
[if] not working

### ISSUE THREAD

**Issue by Nefrasky** [ThereforeGames/unprompted#42]
The following :
```
[set format]
    {choose}portrait|landscape{/choose}
[/set]

[if format="portrait"]
    {sets width=512 height=768}
[/if]
[elif format="landscape"]
    {sets width=960 height=512}
[/elif]
```
does not work at all.

When printing the format variable, I do get either "portrait" or "landscape" but the [if][elif] is never entered.
I tried adding dummy text to print in the if, but it never print.

I also tried to switch from text to int, same result :
```
[set format]
    {choose}1|2{/choose}
[/set]

[if format=1]
    {sets width=512 height=768}
[/if]
[elif format=2]
    {sets width=960 height=512}
[/elif]
```

Am I doing something wrong or is this a bug ?

Sidenote, when I write the following :
```
[set format]
    {choose}
        portrait
        landscape
    {/choose}
[/set]
```
It chooses between "portrait", "landscape" and ""
I feel like this is not the intended result too.

**Comment by ThereforeGames** [comment]
Hi @Cook01. Thank you for reaching out!

It looks like the `[set]` shortcode does not strip your newline or indentation characters, which is why the conditional checks fail. If you modify the first line to the following, it should work:

```
[set format]{choose}portrait|landscape{/choose}[/set]
```

I will need to consider an app-wide solution for stripping these characters from all content blocks, probably with an option to enable/disable such behavior.

**Comment by Nefrasky** [comment]
oh, ok.
Thanks.

I will test it and get back to you.
