### ISSUE TITLE
Feature request: multi-step prompts with user guidance

### ISSUE THREAD

**Issue by OEvgeny** [ThereforeGames/unprompted#65]
The idea came from [this post](https://www.reddit.com/r/StableDiffusion/comments/10xqwjm/comment/j7tr5dv/?utm_source=share&utm_medium=web2x&context=3). The workflow would be as follows:

1. generate a set of images using initial settings. It'd be great if users could skip the step
2. let them pick some of images and add their's if they wish
3. run the next step only with images picked/added

**Comment by ThereforeGames** [comment]
Hi @OEvgeny,

Thank you for the suggestion!

Could you help me understand how this would differ from running "batch img2img" from the WebUI?

You can also do something similar with `[filelist]`, `[length]` and a `[for]` loop. Example: you save your initial images into a "reprocess" folder, deleting any images you don't like. Then, use the aforementioned shortcodes to run img2img on every file in the "reprocess" folder, either inside of an `[after]` block or perhaps with `[enable_multi_images]`.

As far as I can tell, the only way to further streamline the process would be incorporating a UI that lets you pick which images to keep, rather than doing it in your native file manager. But the level of UI development required for this is perhaps outside the scope of an extension, given that Gradio is fairly limited in what it can do (A1111 is already pushing it outside of its comfort zone.)

Thoughts?

**Comment by OEvgeny** [comment]
Yeah, that's pretty it, given that the UI can't be adjusted to pick the images, and except maybe the stop between the iterations so users have an ability to delete Images they don't want to further process.

Another thing I wasn't able to figure out with Unprompted in this context yet is how can I make three step workflows work with a single unprompted run. E.g. text2img (batch 20) -> pick by user (10) -> img2img (10) -> pick by user (5) -> img2img (5)
