### ISSUE TITLE
[Choose] Tags Don't Select Different Lines Between Batches

### ISSUE THREAD

**Issue by unwize** [ThereforeGames/unprompted#7]
I have a template structure like so:

`a.txt = "a scene with [file b]"`

```
b.txt = "
[choose]
line1
line2
line3
[/choose]
"
```

When I run a batch count> 1,  `[file b]` always selects the same line for each batch.

Increasing depth such that

```
a.txt = "
[choose]
first scene with [file b]
second scene with [file b]
[/choose]
"
```

`[file a]` results in selecting the same line from a.txt and same line from b.txt for each run. 

Is this a problem with [choose] or a problem with my setup?

**Comment by IkariDevGIT** [comment]
yes, please fix this

**Comment by ThereforeGames** [comment]
Hi,

This was intentional behavior - I find it useful to compare results with the same random prompt on a higher batch count.

That said, I just released an update that adds `batch_support` to config.json. It will produce a random prompt for every image in a batch process, and it is enabled by default. Let me know if it works as you would expect.

One limitation: I'm not sure there's an easy way to update the text in the WebUI underneath each image. It only displays the prompt for the first image. However, if you save an image or review the command line output, you will find the additional prompts there.

If anyone knows of a better solution, I'm all ears. 😊

**Comment by unwize** [comment]
Behaves as expected. Thank you.
